import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
    await page.goto('http://localhost:3000/auth');
    await page.getByRole('tab', { name: 'Registro' }).click();
    await page.getByRole('textbox', { name: 'Ingresa tu nombre' }).click();
    await page.getByRole('textbox', { name: 'Ingresa tu nombre' }).fill('Juan');
    await page.getByRole('textbox', { name: 'Ingresa tu apellido' }).click();
    await page.getByRole('textbox', { name: 'Ingresa tu apellido' }).fill('Rodriguez');
    await page.getByRole('textbox', { name: 'Ingresa tu correo' }).click();
    const uniqueEmail = `testuser_${Date.now()}@example.com`;
    await page.getByRole('textbox', { name: 'Ingresa tu correo' }).fill(uniqueEmail);
    await page.getByRole('textbox', { name: 'Ingresa tu contraseña' }).click();
    await page.getByRole('textbox', { name: 'Ingresa tu contraseña' }).fill('Password1*');
    await page.getByRole('button', { name: 'Registrarse' }).click();
    await page.getByRole('link', { name: 'Crear nuevo caso' }).click();
    await page.getByRole('button', { name: 'Cabecera' }).click();
    await page.getByRole('spinbutton', { name: 'Versión' }).click();
    await page.getByRole('spinbutton', { name: 'Versión' }).fill('1');
    await page.getByRole('textbox', { name: 'Código' }).click();
    await page.getByRole('textbox', { name: 'Código' }).fill('123');
    await page.getByRole('button', { name: 'Ingresa una fecha' }).click();
    await page.getByRole('button', { name: 'Monday, May 19th,' }).click();
    await page.getByRole('button', { name: 'Introducción' }).click();
    await page.getByRole('textbox', { name: 'Nombre del Proyecto' }).click();
    await page.getByRole('textbox', { name: 'Nombre del Proyecto' }).fill('Trabajo');
    await page.getByRole('textbox', { name: 'Institución(es) Participantes' }).click();
    await page.getByRole('textbox', { name: 'Institución(es) Participantes' }).fill('Trabajo');
    await page.getByRole('button', { name: 'Información general' }).click();
    await page.getByRole('combobox').first().click();
    await page.getByLabel('Riesgo mínimo').getByText('Riesgo mínimo').click();
    await page.getByRole('combobox').nth(1).click();
    await page.getByLabel('Adultos mayores de 18 años').getByText('Adultos mayores de 18 años').click();
    await page.getByRole('combobox').filter({ hasText: 'Seleccione una opción' }).click();
    await page.getByLabel('Intervención (psicosocial,').getByText('Intervención (psicosocial,').click();
    await page.getByRole('textbox', { name: '4. ¿Por qué se debe realizar' }).click();
    await page.getByRole('textbox', { name: '4. ¿Por qué se debe realizar' }).fill('Trabajo');
    await page.getByRole('textbox', { name: '5. ¿Cuál es el objetivo de' }).click();
    await page.getByRole('textbox', { name: '5. ¿Cuál es el objetivo de' }).fill('Trabajo');
    await page.getByRole('textbox', { name: '¿En qué consiste el estudio?' }).click();
    await page.getByRole('textbox', { name: '¿En qué consiste el estudio?' }).fill('Trabajo');
    await page.getByRole('textbox', { name: '7. ¿Cuáles son las molestias' }).click();
    await page.getByRole('textbox', { name: '7. ¿Cuáles son las molestias' }).fill('Trabajo');
    await page.getByRole('textbox', { name: '8. ¿Cuáles son los beneficios' }).click();
    await page.getByRole('textbox', { name: '8. ¿Cuáles son los beneficios' }).fill('Trabajo');
    await page.getByRole('textbox', { name: '9. ¿Existe confidencialidad' }).click();
    await page.getByRole('textbox', { name: '9. ¿Existe confidencialidad' }).fill('Trabajo');
    await page.getByRole('textbox', { name: '10. ¿Existen procedimientos' }).click();
    await page.getByRole('textbox', { name: '10. ¿Existen procedimientos' }).fill('Trabajo');
    await page.getByRole('textbox', { name: '11. Expresar el compromiso de' }).click();
    await page.getByRole('textbox', { name: '11. Expresar el compromiso de' }).fill('Trabajo');
    await page.getByRole('textbox', { name: '12. ¿Existe alguna obligación' }).click();
    await page.getByRole('textbox', { name: '12. ¿Existe alguna obligación' }).fill('Trabajo');
    await page.getByRole('textbox', { name: '13. ¿Cuánto tiempo durará mi' }).click();
    await page.getByRole('textbox', { name: '13. ¿Cuánto tiempo durará mi' }).fill('Trabajo');
    await page.getByRole('textbox', { name: '14. ¿Qué sucede si no deseo' }).click();
    await page.getByRole('textbox', { name: '14. ¿Qué sucede si no deseo' }).fill('Trabajo');
    await page.getByRole('textbox', { name: 'Nombre del patrocinador' }).first().click();
    await page.getByRole('textbox', { name: 'Nombre del patrocinador' }).first().fill('Sara');
    await page.getByRole('textbox', { name: 'Nombre de la compañía' }).click();
    await page.getByRole('textbox', { name: 'Nombre de la compañía' }).fill('Apple');
    await page.getByRole('textbox', { name: 'Dirección' }).click();
    await page.getByRole('textbox', { name: 'Dirección' }).fill('Apple');
    await page.locator('select[name="genero_doctor"]').selectOption('Masculino');
    await page.getByRole('textbox', { name: 'Nombre del investigador' }).click();
    await page.getByRole('textbox', { name: 'Nombre del investigador' }).fill('Juan');
    await page.getByPlaceholder('Celular del investigador').click();
    await page.getByPlaceholder('Celular del investigador').fill('321054826');
    await page.getByRole('textbox', { name: 'Director/a Of. Investigaciones' }).click();
    await page.getByRole('textbox', { name: 'Director/a Of. Investigaciones' }).fill('Laura');
    await page.getByRole('textbox', { name: 'celular o correo email' }).click();
    await page.getByRole('textbox', { name: 'celular o correo email' }).fill('juan@gmail.com');
    await page.getByRole('button', { name: 'Autorización' }).click();
    await page.getByRole('textbox', { name: 'nombre del estudio' }).click();
    await page.getByRole('textbox', { name: 'nombre del estudio' }).fill('Gripe');
    await page.locator('select[name="genero_inv_principal"]').selectOption('Masculino');
    await page.getByRole('textbox', { name: 'nombre', exact: true }).click();
    await page.getByRole('textbox', { name: 'nombre', exact: true }).fill('Gripe');
    await page.getByPlaceholder('número de celular').click();
    await page.getByPlaceholder('número de celular').click();
    await page.getByPlaceholder('número de celular').fill('321054826');
    await page.getByPlaceholder('télefono').click();
    await page.getByPlaceholder('télefono').fill('321054826');
    await page.getByPlaceholder('ext. ').click();
    await page.getByPlaceholder('ext. ').fill('57');
    await page.getByRole('textbox', { name: 'nombre presidente' }).click();
    await page.getByRole('textbox', { name: 'nombre presidente' }).fill('Juan');
    await page.getByRole('button', { name: 'Previsualizar PDF' }).click();
    await page.getByRole('button', { name: 'next page' }).click();
    await page.getByRole('button', { name: 'rotate 90 degrees' }).click();
    await page.getByRole('button', { name: 'rotate 90 degrees' }).click();
    await page.getByRole('button', { name: 'rotate 90 degrees' }).click();
    await page.getByRole('button', { name: 'rotate 90 degrees' }).click();
    await page.getByRole('button', { name: 'zoom' }).click();
    await page.getByRole('menuitem', { name: '50%', exact: true }).click();
    await page.getByRole('button', { name: 'zoom' }).click();
    await page.getByRole('menuitem', { name: '100%' }).click();
    await page.getByRole('button', { name: 'Guardar caso' }).click();
    await page.getByRole('button', { name: 'Open menu' }).click();
    await page.getByRole('menuitem', { name: 'Ver PDF' }).click();
    await page.getByRole('button', { name: 'Cerrar' }).click();
    await page.getByRole('button', { name: 'Vistas' }).click();
    await page.getByRole('menuitemcheckbox', { name: 'Versión' }).click();
    await page.getByRole('button', { name: 'Vistas' }).click();
    await page.getByRole('menuitemcheckbox', { name: 'Nombre Proyecto' }).click();
    await page.getByRole('button', { name: 'Vistas' }).click();
    await page.getByRole('menuitemcheckbox', { name: 'Nombre Proyecto' }).click();
    await page.getByRole('button', { name: 'Open menu' }).click();
    await page.getByRole('menuitem', { name: 'Eliminar' }).click();
    await page.getByPlaceholder('ELIMINAR').fill('ELIMINAR');
    await page.locator('div').filter({ hasText: /^ELIMINAR$/ }).click();
    await page.getByRole('button', { name: 'ELIMINAR' }).click();
    await page.getByRole('button', { name: 'Ajustes' }).click();
    await page.getByRole('link', { name: 'Cuenta' }).click();
    await page.getByRole('textbox', { name: 'Nombre' }).dblclick();
});