config:
  target: "{{ $env.BACKEND_URL }}{{ $env.CONVENTION_API }}"  
  processor: "../dist/hooks/authHook.js"
  http:
    defaults:
      headers:
        Content-Type: "application/json"
        Cookie: "{{ cookies }}"
  phases:
    - name: "Login Spike"
      duration: 60
      arrivalRate: 30

plugins:
  report: {}

scenarios:
  - name: "Login Load Test"
    flow:
      - post:
          url: "/auth/login"
          json:
            email: "{{ $env.ADMIN_EMAIL }}"
            password: "{{ $env.ADMIN_PASSWORD }}"
      - think: 2
      - get:
          url: "/auth/me"
